# All times and delays are in ticks.
# 20 ticks = 1 second
# change above

version: 1

# Which language file will the plugin use for the messages
lang: 'pt-BR'


# Multiplicative modifier for the letters' time to arrive
distance-modifier: 1.0 # 1.0 - standard

# Time it takes for a parrot to be removed after it spawns
despawn-delay: 100 # 5 seconds

# Time before a parrot is respawned, when a letter is ignored
resend-delay: 100 # 5 seconds

# Time to arrive when a receiver is on a different dimension then the sender
different-dimension-delay: 1200 # 60 seconds


# The least amount of time a letter can take to arrive
minimum-send-time: 100 # 5 seconds


# Delay before a letter will be sent when a user joins the server
on-join-delay: 200 # 10 seconds

# Delay before a letter will be sent when a user exits a blocked gamemode
on-gamemode-delay: 100 # 5 seconds

# Delay before a letter will be sent when a user exits a blocked world
on-world-change-delay: 200 # 10 seconds

# Delay before a letter will be sent when a user enables receiving letters
on-enable-letters-delay: 100 # 5 seconds


letters:
  # Rather or not should the letters have a custom model data
  use-custom-model-data: false
  # CustomModelData of regular letters
  letter-model-data: 100
  # CustomModelData of anonymous letters
  anon-letter-model-data: 101



courier:
  # Entity Type (parrot recommended)
  # DO NOT CHANGE
  entity-type: PARROT
  #Options below only work if the entity is set to PARROT
  #  variant for regular letters
  pigeon-variant: BLUE
  # Parrot variant for anonymous letters
  crow-variant: GRAY


# List of gamemodes a user can't receive a letter on
blocked-gamemodes: [SPECTATOR]
# List of worlds a user can't receive a letter on
blocked-worlds: []

